services:
    migrate:
        build: .
        container_name: beautyflow-api-migrate
        restart: "no"
        command: >
            sh -c "until printf '' 2>>/dev/null >/dev/tcp/beautyflow_api/5432; do
                     echo 'Aguardando o banco de dados...';
                     sleep 1;
                   done;
                   alembic upgrade head"
        environment:
            - DATABASE_URL=${DATABASE_URL}
        networks:
        - beautyflow-network
        
    api:
        build: .
        expose:
            - '8000'
        container_name: beautyflow-api
        restart: 'always'
        depends_on:
            migrate:
                condition: service_completed_successfully
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - ALGORITHM=${ALGORITHM}
            - USER_SECRET_KEY=${USER_SECRET_KEY}
            - INTEGRATION_SECRET_KEY=${INTEGRATION_SECRET_KEY}
            - BUSINESS_INTEGRATION_SECRET_KEY=${BUSINESS_INTEGRATION_SECRET_KEY}
            - USER_ACCESS_TOKEN_EXPIRE_MINUTES=${USER_ACCESS_TOKEN_EXPIRE_MINUTES}
            - USER_REFRESH_TOKEN_EXPIRE_DAYS=${USER_REFRESH_TOKEN_EXPIRE_DAYS}
            - INTEGRATION_TOKEN_EXPIRE_DAYS=${INTEGRATION_TOKEN_EXPIRE_DAYS}
            - BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES=${BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES}
        networks:
            beautyflow-network:
                aliases:
                - beautyflow-api
            n8n-network:
                aliases:
                - beautyflow-api

networks:
    beautyflow-network:
        external: true

    n8n-network:
        external: true