"""add email to professional

Revision ID: 287d9cbe2ac9
Revises: 81adade96d86
Create Date: 2026-05-14 20:12:00.945608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287d9cbe2ac9'
down_revision: Union[str, Sequence[str], None] = '81adade96d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("professionals", "email")
    # ### end Alembic commands ###
