"""add client and integration table, add relation business_integration

Revision ID: 2ea3b5e0d5a1
Revises: b4d26a017699
Create Date: 2026-03-02 18:52:04.188890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ea3b5e0d5a1'
down_revision: Union[str, Sequence[str], None] = 'b4d26a017699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_wpp', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'phone', name='uq_client_business_phone')
    )
    op.alter_column('appointments', 'start_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'end_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_professional_weekday'), 'availabilities', type_='unique')
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('businesses_api_key_key'), 'businesses', type_='unique')
    op.drop_constraint(op.f('businesses_name_key'), 'businesses', type_='unique')
    op.create_index(op.f('ix_businesses_timezone'), 'businesses', ['timezone'], unique=False)
    op.drop_column('businesses', 'api_key')
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    userrole_enum = postgresql.ENUM(
        'SUPER_ADMIN',
        'ADMIN',
        'USER',
        name='userrole'
    )
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole;")
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_business_email', 'users', ['business_id', 'email'])
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_user_business_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'business_id')
    op.alter_column('services', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.add_column('businesses', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_businesses_timezone'), table_name='businesses')
    op.create_unique_constraint(op.f('businesses_name_key'), 'businesses', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('businesses_api_key_key'), 'businesses', ['api_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('businesses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_professional_weekday'), 'availabilities', ['professional_id', 'weekday'], postgresql_nulls_not_distinct=False)
    op.alter_column('appointments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('appointments', 'end_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('appointments', 'start_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table('clients')
    op.drop_table('integrations')
    # ### end Alembic commands ###
