"""add normalized_names on services and professionals

Revision ID: 469d81335791
Revises: 9db146cdf90a
Create Date: 2026-05-13 18:31:37.676582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '469d81335791'
down_revision: Union[str, Sequence[str], None] = '9db146cdf90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('scheduled', 'canceled', 'completed', name='appointmentstatus'),
               server_default='scheduled',
               existing_nullable=False)
    op.alter_column('business_integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('businesses', 'type',
               existing_type=postgresql.ENUM('barbershop', 'salon', 'clinic', name='businesstype'),
               nullable=False)
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('businesses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.drop_column('clients', 'name_wpp')
    op.alter_column('integrations', 'type',
               existing_type=postgresql.ENUM('automation', name='integrationtype'),
               nullable=False)
    op.alter_column('integrations', 'api_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)

    op.add_column(
        'professionals',
        sa.Column(
            'normalized_name',
            sa.String(length=50),
            nullable=False,
            server_default=''
        )
    )
    op.execute("""
        UPDATE professionals
        SET normalized_name = lower(unaccent(name))
    """)
    op.alter_column('professionals', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.create_index(
        'idx_professionals_normalized_name_trgm',
        'professionals',
        ['normalized_name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={
            'normalized_name': 'gin_trgm_ops'
        },
    )
    op.alter_column(
        'professionals',
        'normalized_name',
        server_default=None
    )

    op.add_column(
        'services',
        sa.Column(
            'normalized_name',
            sa.String(length=50),
            nullable=False,
            server_default=''
        )
    )
    op.execute("""
        UPDATE services
        SET normalized_name = lower(unaccent(name))
    """)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.create_index(
        'idx_services_normalized_name_trgm',
        'services',
        ['normalized_name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={
            'normalized_name': 'gin_trgm_ops'
        },
    )
    op.alter_column(
        'services',
        'normalized_name',
        server_default=None
    )

    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    op.drop_index('idx_services_normalized_name_trgm', table_name='services')
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('services', 'normalized_name')

    op.drop_index('idx_professionals_normalized_name_trgm', table_name='professionals')
    op.alter_column('professionals', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('professionals', 'normalized_name')

    op.alter_column('integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('integrations', 'api_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('integrations', 'type',
               existing_type=postgresql.ENUM('automation', name='integrationtype'),
               nullable=True)
    op.add_column('clients', sa.Column('name_wpp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('businesses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('businesses', 'type',
               existing_type=postgresql.ENUM('barbershop', 'salon', 'clinic', name='businesstype'),
               nullable=True)
    op.alter_column('business_integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('scheduled', 'canceled', 'completed', name='appointmentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###