"""new constrants

Revision ID: 6125373668a7
Revises: 9c2f27e899d0
Create Date: 2026-03-04 15:46:02.605364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6125373668a7'
down_revision: Union[str, Sequence[str], None] = '9c2f27e899d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'clients', ['cliente_id'], ['id'], ondelete='cascade')
    op.drop_column('appointments', 'client_name')
    op.drop_column('appointments', 'client_phone')
    op.create_unique_constraint('uq_professional_business_name', 'professionals', ['business_id', 'name'])
    op.create_unique_constraint('uq_service_business_name', 'services', ['business_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_business_name', 'services', type_='unique')
    op.drop_constraint('uq_professional_business_name', 'professionals', type_='unique')
    op.add_column('appointments', sa.Column('client_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'cliente_id')
    # ### end Alembic commands ###
