"""limit name and phone column lengths

Revision ID: 7eba754343ab
Revises: 469d81335791
Create Date: 2026-05-13 18:51:36.132655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eba754343ab'
down_revision: Union[str, Sequence[str], None] = '469d81335791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "businesses",
        "name",
        existing_type=sa.String(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "clients",
        "name",
        existing_type=sa.String(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "integrations",
        "name",
        existing_type=sa.String(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "professionals",
        "name",
        existing_type=sa.String(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "name",
        existing_type=sa.String(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "clients",
        "phone",
        existing_type=sa.String(),
        type_=sa.String(length=13),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "phone",
        existing_type=sa.String(length=13),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "professionals",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "integrations",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "clients",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "businesses",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
