"""updating availabilities primary key

Revision ID: 81adade96d86
Revises: 7eba754343ab
Create Date: 2026-05-13 19:36:43.026238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81adade96d86'
down_revision: Union[str, Sequence[str], None] = '7eba754343ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("availabilities_pkey", "availabilities", type_="primary")
    op.create_primary_key(
        "availabilities_pkey",
        "availabilities",
        ["professional_id", "weekday"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("availabilities_pkey", "availabilities", type_="primary")
    op.create_primary_key(
        "availabilities_pkey",
        "availabilities",
        ["professional_id"],
    )
    # ### end Alembic commands ###
