"""alter type status appointment, use BusinessIntegration

Revision ID: 9c2f27e899d0
Revises: 2ea3b5e0d5a1
Create Date: 2026-03-03 18:34:25.256184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2f27e899d0'
down_revision: Union[str, Sequence[str], None] = '2ea3b5e0d5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_integrations',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('business_id', 'integration_id')
    )

    appointmentstatus_enum = sa.Enum('scheduled', 'canceled', 'completed', name='appointmentstatus')
    appointmentstatus_enum.create(op.get_bind(), checkfirst=True)

    op.execute("ALTER TABLE appointments ALTER COLUMN status TYPE appointmentstatus USING status::appointmentstatus;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('scheduled', 'canceled', 'completed', name='appointmentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('business_integrations')
    # ### end Alembic commands ###
