"""add appointments/availability constraint, and add types

Revision ID: 9db146cdf90a
Revises: 45dc65e9a97e
Create Date: 2026-03-27 18:20:59.772364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db146cdf90a'
down_revision: Union[str, Sequence[str], None] = '45dc65e9a97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_business_id'), 'appointments', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.drop_constraint(op.f('appointments_cliente_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'clients', ['client_id'], ['id'], ondelete='cascade')
    op.drop_column('appointments', 'cliente_id')
    op.create_index(op.f('ix_availabilities_professional_id'), 'availabilities', ['professional_id'], unique=False)
    op.create_index(op.f('ix_business_integrations_business_id'), 'business_integrations', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_integrations_integration_id'), 'business_integrations', ['integration_id'], unique=False)
    
    businesstype_enum = sa.Enum('barbershop', 'salon', 'clinic', name='businesstype')
    businesstype_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE businesses ALTER COLUMN type TYPE businesstype USING type::businesstype;")

    integrationtype_enum = sa.Enum('automation', name='integrationtype')
    integrationtype_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE integrations ALTER COLUMN type TYPE integrationtype USING type::integrationtype;")

    op.drop_index(op.f('ix_businesses_timezone'), table_name='businesses')
    op.create_unique_constraint(None, 'businesses', ['name'])
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=False)
    op.alter_column('integrations', 'api_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'integrations', ['name'])
    op.create_index(op.f('ix_professional_services_professional_id'), 'professional_services', ['professional_id'], unique=False)
    op.create_index(op.f('ix_professional_services_service_id'), 'professional_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_professionals_business_id'), 'professionals', ['business_id'], unique=False)
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_check_constraint(
        "ck_appointments_valid_datetime_range",
        "appointments",
        "start_datetime < end_datetime",
    )

    op.execute("""
        ALTER TABLE appointments
        ADD CONSTRAINT ex_appointments_business_professional_time_conflict
        EXCLUDE USING gist (
            business_id WITH =,
            professional_id WITH =,
            tstzrange(start_datetime, end_datetime, '[)') WITH &&
        )
        WHERE (status = 'scheduled');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.drop_index(op.f('ix_professionals_business_id'), table_name='professionals')
    op.drop_index(op.f('ix_professional_services_service_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_professional_id'), table_name='professional_services')
    op.drop_constraint(None, 'integrations', type_='unique')
    op.alter_column('integrations', 'api_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('integrations', 'type',
               existing_type=sa.Enum('automation', name='integrationtype'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.create_index(op.f('ix_businesses_timezone'), 'businesses', ['timezone'], unique=False)
    op.alter_column('businesses', 'type',
               existing_type=sa.Enum('barbershop', 'salon', 'clinic', name='businesstype'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_business_integrations_integration_id'), table_name='business_integrations')
    op.drop_index(op.f('ix_business_integrations_business_id'), table_name='business_integrations')
    op.drop_index(op.f('ix_availabilities_professional_id'), table_name='availabilities')
    op.add_column('appointments', sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_cliente_id_fkey'), 'appointments', 'clients', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_business_id'), table_name='appointments')
    op.drop_column('appointments', 'client_id')
    op.execute("""
        ALTER TABLE appointments
        DROP CONSTRAINT IF EXISTS ex_appointments_business_professional_time_conflict
    """)

    op.drop_constraint(
        "ck_appointments_valid_datetime_range",
        "appointments",
        type_="check",
    )
    # ### end Alembic commands ###
