import os
from dotenv import load_dotenv

load_dotenv()
ALGORITHM = os.getenv("ALGORITHM")
DATABASE_URL = os.getenv("DATABASE_URL")

USER_SECRET_KEY = os.getenv("USER_SECRET_KEY")
INTEGRATION_SECRET_KEY = os.getenv("INTEGRATION_SECRET_KEY")
BUSINESS_INTEGRATION_SECRET_KEY = os.getenv("BUSINESS_INTEGRATION_SECRET_KEY")

USER_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("USER_ACCESS_TOKEN_EXPIRE_MINUTES"))
USER_REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("USER_REFRESH_TOKEN_EXPIRE_DAYS"))
INTEGRATION_TOKEN_EXPIRE_DAYS = int(os.getenv("INTEGRATION_TOKEN_EXPIRE_DAYS"))
BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES = int(os.getenv("BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES"))