import os
from dotenv import load_dotenv

load_dotenv()
ALGORITHM = os.getenv("ALGORITHM")
SECRET_KEY = os.getenv("SECRET_KEY")

DATABASE_URL = os.getenv("DATABASE_URL")

ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))

INTEGRATION_TOKEN_EXPIRE_DAYS = int(os.getenv("INTEGRATION_TOKEN_EXPIRE_DAYS"))

BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES = int(os.getenv("BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES"))