"""new api_token for integration

Revision ID: 8daa394d93ba
Revises: 6125373668a7
Create Date: 2026-03-10 17:00:32.501540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8daa394d93ba'
down_revision: Union[str, Sequence[str], None] = '6125373668a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_integrations', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('integrations', sa.Column('api_token_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'api_token_hash')
    op.drop_column('business_integrations', 'config')
    # ### end Alembic commands ###
