"""update user table

Revision ID: 97ca3da62906
Revises: 5842ad7c941b
Create Date: 2026-02-23 18:01:26.590650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ca3da62906'
down_revision: Union[str, Sequence[str], None] = '5842ad7c941b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_business_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'business_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_business_id_fkey'), 'users', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
