"""update relationship professional-service

Revision ID: b4d26a017699
Revises: d24a6282b80a
Create Date: 2026-02-23 19:32:29.493752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d26a017699'
down_revision: Union[str, Sequence[str], None] = 'd24a6282b80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_services',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('professional_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional_services')
    # ### end Alembic commands ###
